# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='thought',
            fields=[
                ('content', models.CharField(max_length=140)),
                ('Privacy', models.CharField(choices=[('P', 'Public'), ('F', 'Friends'), ('S', 'Select')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user1', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user2', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(related_name='followed_by', to='Thoughts.UserProfile')),
            ],
        ),
    ]
